### ISSUE TITLE
How to add it to maya?

### ISSUE THREAD

**Issue by faustinozanetto** [ue4plugins/MayaLiveLink#1]
In the documentation it shows the 2018 2019 folders, but in the download i cannot find any

**Comment by missakael** [comment]
зачем выкладывать этот плагин "MayaLiveLinkPlugin2019.Build.cs" с этим расширением ".cs" для Maya нужно расширение .mll к чему людям эти тряски с бубном в Visual studio ?????????? мне для работы в UE4 + Maya эта  Visual studio не нужна. . . . я делаю только Cutscene для 3d фильмов, и как мне использовать этот ваш  MayaLiveLinkPlugin2019.Build.cs

**Comment by AntonPalmqvistGBK** [comment]
The documentation is wrong, since these are just the source files, and not the pre-built binaries.
Would be great if Epic could compile the binaries so we don't have to download and build the full UE4 solution in Visual Studio.

**Comment by DennyLindberg** [comment]
The binaries are in this repository. They just happen to be located in the zip-file under releases. (the button for releases is kinda hard to spot on Github...) Perhaps it would be better if the documentation links directly to the releases page instead of the main page, or that the readme refers the user to the releases page.

https://github.com/ue4plugins/MayaLiveLink/releases

**Comment by AntonPalmqvistGBK** [comment]
Nice find!
Yeah, it's definitely way too hard to find for someone without Github experience.
I just noticed that Epic snuck in the MayaLiveLink to the Unreal Marketplace, where it makes much more sense.
https://www.unrealengine.com/marketplace/en-US/slug/maya-livelink
They didn't have the time to update the docs just yet.

**Comment by nandanph82** [comment]
thank you so much DennyLindberg

**Comment by SimonTherriaultEpic** [comment]
Maya and Mobu plugins are now distributed in the marketplace with precompiled binaries for different software versions. On Git, you can find the binaries precompiled in the release folder, as stated by @DennyLindberg . We'll take not of your suggestion about documentation not being clear about where to find them. 

Thanks!
