### ISSUE TITLE
Where should I download MayaLiveLink 1.0

### ISSUE THREAD

**Issue by pingoomanager** [ue4plugins/MayaLiveLink#10]
Where should I download MayaLiveLink 1.0? I using Unreal 4.21. Can't use MayaLiveLink 2.0

**Comment by mattyjams** [comment]
The most recent Maya Live Link plugin release supports UE 4.27:
https://github.com/ue4plugins/MayaLiveLink/releases/tag/v2.0.427

Those plugins as well as versions that support UE back to version 4.23 are also available from the Marketplace:
https://www.unrealengine.com/marketplace/en-US/product/maya-livelink

We unfortunately no longer support Maya Live Link for versions of Unreal Engine earlier than 4.23.
