### ISSUE TITLE
Maya 2020 missing

### ISSUE THREAD

**Issue by apopanda** [ue4plugins/MayaLiveLink#11]
I have Maya 2020, and wanted to give the plugin a go, but it seems, like the plugin hasn't been updated yet? Is it possible to build it for 2020 somehow? The 2019 version outright says it's incompatible.

**Comment by SpectralInk** [comment]
I too would really like the Maya 2020 version. Been trying to compile it myself, can get the Unreal side to build but having issues getting it to link with the Maya Dev Kit.

**Comment by SpectralInk** [comment]
We were able to get the Maya 2020 version to compile. Here's what you need to know:

The 2016 files contain the main functions, the others just override one function to pass the correct version number. 

It assumes Maya is installed in its default location. If this is not the case, you need to modify the code to point to the correct directory.

Place all the source code in \Engine\Source\Programs\NotForLicensees\MayaLiveLinkPlugin and add our updated *.cs files (in the zip file). Also add the BuildMayaPLugin.xml and BuildMayaPlugin.bat (also in the zip file). It will also look for a readme.txt, so either create a blank one, or remove that line from the xml when it packages everything up. The XML is modified to build only the 2020 version.

run the *.bat from a cmd window.

With luck, it should package the new *,mll in a subfolder.

[MayaLiveLink2020.zip](https://github.com/ue4plugins/MayaLiveLink/files/4548198/MayaLiveLink2020.zip)

**Comment by NicoSteyl** [comment]
There was no "NotForLicensees" file in \Engine\Source\Programs\. I created the folders and copied all the source files like the image below. When I run the bat file, it gives me an error. See the images attached. 

I had to create the last "NotForLiscensees" folder and "MayaLiveLinkPlugin" Subfolder. Then I copied all this stuff from the \Plugins\Marketplace\MayaLiveLink\Source folder:
![explorer_cTk0P8eNrd](https://user-images.githubusercontent.com/62116386/82223073-6e7f5d80-9922-11ea-8195-b9804d274b63.png)


Building Failed. I'm guessing file path miss-match, but have no idea on where to change what...
![cmd_iVJNBhUP3S](https://user-images.githubusercontent.com/62116386/82223107-7f2fd380-9922-11ea-8e37-b213ce3a3e21.png)


Any thoughts on how to proceed?

**Comment by warbands** [comment]
Any movement on getting a Maya 2020 version of the plugin compiled? Also is anyone running this on macOS?

**Comment by mlveggo** [comment]
See https://github.com/ue4plugins/MayaLiveLink/pull/12 for Maya 2016-2020 plugin.

**Comment by SamGeeee** [comment]
@mlveggo @SpectralInk would you mind providing a step by step guide, I followed what was written but ran into the same problems as @DigitalDirectSA.

**Comment by mlveggo** [comment]
The above error states to install .net framework 4.6.0 or higher.

**Comment by mattyjams** [comment]
Support for building the plugin for Maya 2020 and Maya 2022 is now available. Maya 2020 support was added in c2e2ef7fe5b0b734b8dee6e0d1dab41499cf52d0, and Maya 2022 support was added in 085f0bb7612183094e04dd140756b0149b1ff365.
