### ISSUE TITLE
Will blendshapes ever be supported?

### ISSUE THREAD

**Issue by emarusso** [ue4plugins/MayaLiveLink#16]
Hi,

I would like this plugin to support the export of blendshape weights, just like the MotionBuilder LiveLink does.
I started to study the maya sdk to find a way to implement it, is there a techical reason why this is not implemented in this plugin?
If there's not, could give me some guidelines on how to implement it, so I can do it myself ?

Thanks

**Comment by mattyjams** [comment]
Good suggestion, and in fact the recently released Unreal Live Link for Autodesk Maya plugin adds some initial support for blendshapes. You can find that plugin on the Unreal Engine Marketplace here:

https://www.unrealengine.com/marketplace/en-US/product/f2e37c4b943f4337b352e1639fa4ebe3

Or visit the Autodesk GitHub repo for the plugin here:

https://github.com/Autodesk/LiveLink

The older Maya Live Link plugin is now deprecated, so the new plugin and repo are where you'll be able to find new development and support from now on.

Closing this out...
