### ISSUE TITLE
having problem with imorting MayaLiveLinkUI.py in Maya 2020 and 2022

### ISSUE THREAD

**Issue by MAKSIM7** [ue4plugins/MayaLiveLink#18]
MayaLiveLinkUI;
// Error: line 1: AttributeError: file C:/Users/PROF/Documents/maya/2020/scripts/MayaLiveLinkUI.py line 110: 'module' object has no attribute 'LiveLinkConnectionStatus' // 
Version UE4.26 and UE4.27
Update 2020 and preferably 2022?

**Comment by MAKSIM7** [comment]
There are no compiled files it turns out for version 2020 and 2022. Can you compile?
In MAYA 2022 Python 3 is used in priority, as I understand it can be compiled for python 3 or also register?:
"...Maya2022\bin\maya.exe" -pythonver 2
https://help.autodesk.com/view/MAYAUL/2022/ENU/?guid=GUID-C0F27A50-3DD6-454C-A4D1-9E3C44B3C990

**Comment by mattyjams** [comment]
Plugin binaries for both Maya 2020 and Maya 2022 are included in the latest release:
https://github.com/ue4plugins/MayaLiveLink/releases/tag/v2.0.427
These plugins are also available from the Marketplace:
https://www.unrealengine.com/marketplace/en-US/product/maya-livelink
