### ISSUE TITLE
Maya 2022 error "Cannot find procedure "MayaLiveLinkRefreshConnectionUI"

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [ue4plugins/MayaLiveLink#19]
I can't make LiveLink work in Maya 2022.

Steps I did:

1. Installed the pluging from the marketplace
2. Copy the "2022" folder to <...\Maya2022\plug-ins>
3. In Maya I browsed and selected the "MayaLiveLinkPlugin2022.mll"
4. // Error: line 1: Cannot find procedure "MayaLiveLinkRefreshConnectionUI"

**Comment by mattyjams** [comment]
The `MayaLiveLinkRefreshConnectionUI` command that it's referring to is defined in the `MayaLiveLinkUI.py` Python script that is bundled with the plugin, so you'll want to make sure that the `MayaLiveLinkUI` plugin loads successfully as well.

The recently released Unreal Live Link for Autodesk Maya plugin provides an installer that should help ensure that the plugin and any additional supporting files are installed correctly, so you may want to give that new plugin a try if you're still encountering this issue. You can find that plugin on the Unreal Engine Marketplace here:

https://www.unrealengine.com/marketplace/en-US/product/f2e37c4b943f4337b352e1639fa4ebe3

The older Maya Live Link plugin is now deprecated, so if you still need support, the best place to find it would be the Autodesk GitHub repo for the new plugin here:

https://github.com/Autodesk/LiveLink

Closing this out...
