### ISSUE TITLE
having problem with imorting MayaLiveLinkUI.py in Maya 2016

### ISSUE THREAD

**Issue by Nejuz7** [ue4plugins/MayaLiveLink#3]
is there something wrong with  .py file??
or is this with maya ?

 it showing this error when I try to load MayaLiveLinkUI

// Error: line 1: TypeError: file C:/Program Files/Autodesk/Maya2016/plug-ins/2016/MayaLiveLinkUI.py line 22: Invalid flag 'adjustableColumn' //

**Comment by Nejuz7** [comment]
It's working now 

I just removed "adjustableColumn=2" from that file and reimported.
now it's working...

**Comment by SimonTherriaultEpic** [comment]
This is fixed internally. Next time we push to git, it will be ok. Removing the adjustableColumn was the right thing to do.
