### ISSUE TITLE
.cpp won't be recognized as a plugin file. Is there a .mll?

### ISSUE THREAD

**Issue by SpencerHamm** [ue4plugins/MayaLiveLink#4]
Maya 2018 won't recognize my MayaLiveLinkPlugin.cpp as a plug-in file. Is there a MayaLiveLinkPlugin2018.mll file like it shows in the documentation?

**Comment by SpencerHamm** [comment]
**SOLVED**: Found the files that are shown in the documentation!

https://github.com/ue4plugins/MayaLiveLink/releases

**Comment by SimonTherriaultEpic** [comment]
Binaries (mll) are released in zips when we create releases. Only the sources are distributed individually.
