### ISSUE TITLE
How can i get the MayalivelinkPlugin2018.mll?And how can i upgrade it?

### ISSUE THREAD

**Issue by StarTHEViper** [ue4plugins/MayaLiveLink#6]
How can i get the MayalivelinkPlugin2018.mll?And how can i upgrade it?

**Comment by wandal1** [comment]
Same here, can't find this file
BuildMayaPlugin.Bat from v.2.0 didn't work for me

**Comment by StarTHEViper** [comment]
i find that on marketplace,called maya livelink.It works





---Original---

**Comment by PatrickBoutotEpic** [comment]
You may download the latest version of the Unreal Engine Marketplace. The github repro is used by programmers that want the source code to build or modify their version.
