### ISSUE TITLE
Request for a new release for maya 2020

### ISSUE THREAD

**Issue by emkuzet** [ue4plugins/MayaLiveLink#7]
Hey guys can we expect any ETA for maya 2020 ?
Thanks a lot and happy new year!

**Comment by Brianrossney** [comment]
I definitely second that request. That said, the 2019 download is lacking the *.ml script. Only the *py for  the UI is there.

**Comment by SpectralInk** [comment]
posted on another thread how you can compile for 2020

**Comment by mattyjams** [comment]
Plugin binaries for both Maya 2020 and Maya 2022 are included in the latest release:
https://github.com/ue4plugins/MayaLiveLink/releases/tag/v2.0.427
These plugins are also available from the Marketplace:
https://www.unrealengine.com/marketplace/en-US/product/maya-livelink
