### ISSUE TITLE
Need 2019 Folder like in the documentation

### ISSUE THREAD

**Issue by s34m** [ue4plugins/MayaLiveLink#8]

**Comment by SimonTherriaultEpic** [comment]
Are you talking about the source code our the release zip file?

**Comment by s34m** [comment]
The release zip file. There should be a foulder with 2019 but it isn't there.

**Comment by mattyjams** [comment]
Plugin binaries for Maya 2019, as well as Maya 2020 and Maya 2022, are included in the latest release:
https://github.com/ue4plugins/MayaLiveLink/releases/tag/v2.0.427
These plugins are also available from the Marketplace:
https://www.unrealengine.com/marketplace/en-US/product/maya-livelink
