### ISSUE TITLE
MayaLiveLinkPlugin2019.mll?

### ISSUE THREAD

**Issue by RyDarling** [ue4plugins/MayaLiveLink#9]
Following the instructions found here:
https://docs.unrealengine.com/en-US/Engine/Animation/LiveLinkPlugin/ConnectingUnrealEngine4toMayawithLiveLink/index.html

I'm a bit confused. I downloaded the file from Github and I don't see the "MayaLiveLinkPlugin2019.mll". I only see the .py and .cs file formats. 

How do I get the file "MayaLiveLinkPlugin2019.mll"?

**Comment by SimonTherriaultEpic** [comment]
You need to go in the Release section of the repository and there download the Release zip file which will include each year mll.

**Comment by WilliamVFX** [comment]
MayaLiveLinkPlugin2019.mll ?? 

They could share the file

**Comment by srlake31470** [comment]
I don't see the Release section either to GET the 2019.mll ??? What are all these other 2019 and earlier file types?  There's indication as to how to install this.  The readme text, points to an older UE documentation.

**Comment by jpnl87** [comment]
The files are in the engine at C:\Program Files\Epic Games\UE_4.24\Engine\Plugins\Marketplace\MayaLiveLink\Binaries\2019.

**Comment by mattyjams** [comment]
Plugin binaries for Maya 2019, as well as Maya 2020 and Maya 2022, are included in the latest release:
https://github.com/ue4plugins/MayaLiveLink/releases/tag/v2.0.427
These plugins are also available from the Marketplace:
https://www.unrealengine.com/marketplace/en-US/product/maya-livelink
